server {
 listen 80;
 server_name camsync.liuguofeng.com;
 root /home/wwwroot/camsync.liuguofeng.com;
 location ^~ /.well-known/acme-challenge/ { root /home/wwwroot/default; }
 location / { try_files $uri $uri/ =404; }
}
